
import { Rider } from './rider';

export const RIDERS: Rider[] = [
    {
        id: 1,
        firstName: "Barry",
        lastName: "Tannenbaum",
        email: "barry.tannenbaum@gmail.com",
        cell: "6033200763",
        monAm: 1,
        monPm: 3,
        tueAm: 1,
        tuePm: 4,
        thuAm: 1,
        thuPm: 4,
    },
    {
        id: 2,
        firstName: "Kent",
        lastName: "Glossop",
        email: "kent@glossop.com",
        cell: "6031234567",
        monAm: 2,
        monPm: 4,
        tueAm: 2,
        tuePm: 4,
        thuAm: 2,
        thuPm: 4,
    },
    {
        id: 3,
        firstName: "Pablo",
        lastName: "Halpern",
        email: "pablo@halpern.com",
        cell: "6031234567",
        monAm: 2,
        monPm: 4,
        tueAm: 2,
        tuePm: 4,
        thuAm: 2,
        thuPm: 4,
    },
    {
        id: 4,
        firstName: "Judy",
        lastName: "Ward",
        email: "judy@ward.com",
        cell: "6031234567",
        monAm: 1,
        monPm: 3,
        tueAm: 1,
        tuePm: 3,
        thuAm: 1,
        thuPm: 3,
    },
    {
        id: 5,
        firstName: "Bob",
        lastName: "Monteleone",
        email: "bob@monteleone.com",
        cell: "6031234567",
        monAm: 1,
        monPm: 3,
        tueAm: 1,
        tuePm: 3,
        thuAm: -1,
        thuPm: -1,
    },
];
